---
- block:
  - set_fact:
      packages:
        - bind
        - bind-utils
        - firewalld
        - haproxy
        - httpd
        - vim
        - bash-completion
        - libselinux-python
        - podman
        - nfs-utils
  
  - set_fact:
      dhcppkgs:
        - dhcp
        - syslinux
        - tftp-server
  
  - set_fact:
      owner: nfsnobody
      group: nfsnobody
  
  - set_fact:
      services:
        - named
        - haproxy
        - httpd
        - rpcbind
        - nfs-server
        - nfs-lock
        - nfs-idmap
  when: ansible_distribution_major_version == "7"

- block:
  - set_fact:
      packages:
        - bind
        - bind-utils
        - firewalld
        - haproxy
        - httpd
        - vim
        - bash-completion
        - python3-libselinux
        - podman
        - nfs-utils
  
  - set_fact:
      dhcppkgs:
        - dhcp-server
        - syslinux
        - tftp-server
  
  # See Fedora Wiki for changes:
  # https://fedoraproject.org/wiki/Changes/RenameNobodyUser
  - set_fact:
      owner: nobody
      group: nobody
  
  - set_fact:
      services:
        - named
        - haproxy
        - httpd
        - rpcbind
        - nfs-server
  when: ansible_distribution_major_version == "8"
